version: '3.8'

services:
  mongo:
    container_name: laundromat-db
    image: mongo:7.0.8
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart: always
    volumes:
      - ./volume/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: .
      dockerfile: ./docker-env/DockerFile_backend
    container_name: laundromat-backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: ./docker-env/DockerFile_frontend
    container_name: laundromat-frontend
    ports:
      - "3000:3000"
    expose:
      - "3000"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - backend